# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773ff18010ec46ff9cb08f8fdf481564718068de49ac47a799d06ad187ceea2b619312bd429e6ed81b68f1440c86f464eb5a4f340dd75ce4eba499e938bd80c3

test:
  secret_key_base: e27f02b6e8c266fe042a39a3997de3eabc185a9369e64c646b0a1ed165a321d62f32098d2c6c08cada60a267b3504063cfcb9f4a4f20cebdf7dbd3101309d1a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
